### ISSUE TITLE
Issue when deploying cloudformation template - sha512 and bucket dependency

### ISSUE THREAD

**Issue by andreav** [awslabs/amazon-kinesis-data-generator#40]
Hello,
I open this issue to track fixes I had to do for deploying cloudformation template.

I had 2 errors.

First one was:

`name 'RunTimeError' is not defined`

I fixed it changing the sha512 in the template from this:

`bbe80f52ec7a246c065069f2bb0112a1a968472e6b48946ab88d73e5284787cd56acbd1d7adaa07a8120f3e1bd8d6644b96d18d7f0d7a2e60013d77b00d07eaa`

to this:

`779f78833de27c4523d27b0f792c7d3be7070fbe4bca76d480af2cb030049601e0081d44712c420e972c4bb9546c4167368671135ea0e62fe7d5d026eea584f6`

Once fixed the first error, the second one appered: "cannot get bucket Arn"

I fixed this error by adding a `DependsOn` to `StagingLambdaRole`,
from this:

```
StagingLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
```
to this:

```
  StagingLambdaRole:
    Type: "AWS::IAM::Role"
    DependsOn: StagingS3Bucket
    Properties:
```
